class Config:
    ENVIRONMENT_SIZE = 512
    GRID_SIZE = 64
    GRID_NUMBER = ENVIRONMENT_SIZE // GRID_SIZE
    NUM_OF_PLANES = 4
    NUM_OF_FIRES = 4
    MAX_STACK = 3
    MAX_INTENSITY = 3
    SPREAD_TIMESTEP = 6000
    INTENSITY_TIMESTEP = 6000
    MAX_MOVE = 500000
    MAX_FPS = 15
    NUM_ACTIONS = 9
    HIDDEN_DIM = 64
    PROXIMITY_THRESHOLD = 2

    # Reward shaping
    EXTINGUISH_REWARD = 100
    CLOSE_TO_FIRE_REWARD = 3
    EMPTY_STACK_PENALTY = 1
    NOOP_PENALTY = 0.6
    MIN_PROXIMITY_REWARD = 0.4
    SPEED_PENALTY_SCALE = 0.1
    MAX_PENALTY = 10

    # Training configuration
    CLIP_EPSILON = 0.2
    VALUE_LOSS_COEF = 0.5
    ENTROPY_LOSS_COEF = 0.01
